#Minecraft server properties
#Sun Jun 07 12:48:41 BST 2015
spawn-protection=0
generator-settings=
op-permission-level=3
allow-nether=true
level-name=world
enable-query=true
query.port=25565
allow-flight=true
announce-player-achievements=true
server-id=fluffle
server-name=fs.pl0rt.org
server-port=25565
level-type=rwg
enable-rcon=false
level-seed=
force-gamemode=false
server-ip=
max-build-height=256
spawn-npcs=true
white-list=false
spawn-animals=true
hardcore=false
snooper-enabled=false
online-mode=true
resource-pack=
pvp=true
difficulty=3
enable-command-block=false
gamemode=0
player-idle-timeout=0
max-players=20
spawn-monsters=true
generate-structures=true
simulation-distance=8
view-distance=12
motd=Greg Some Trees
